"""djangoProject URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from DoQs import views
from django.views.generic import TemplateView

urlpatterns = [
    path('', views.login, name='login'),
    path('loginan', views.loginan, name='loginan'),
    path('register', views.register, name='register'),
    path('registeran', views.registeran, name='registeran'),
    path('addhuman', views.addhuman, name='addhuman'),
    path('addhumanan', views.addhumanan, name='addhumanan'),
    path('person', views.person, name='person'),
    path('addhn', views.addhn, name='addhn'),
    path('deletehn', views.deletehn, name='deletehn'),
    path('edithn', views.edithn, name='edithn'),
    path('updatehn', views.updatehn, name='updatehn'),
    path('clogin', views.clogin, name='clogin'),
    path('cloginan', views.cloginan, name='cloginan'),
    path('booking', views.booking, name='booking'),
    path('bookingv2', views.bookingv2, name='bookingv2'),
    path('deletehnone', views.deletehnone, name='deletehnone'),
    path('personinfo', views.personinfo, name='personinfo'),
    path('staff', views.staff, name='staff'),
    path('addDPM', views.addDPM, name='addDPM'),
    path('gsession', views.getsession),
    path('dessession', views.dessession, name='dessession'),
    path('logout', views.logout, name='logout'),
    path('settingHn', views.settingHn, name='settingHn'),
    path('addstaff', views.addstaff, name='addstaff'),
    path('mnbook', views.mnbook, name='mnbook'),
    path('sthos', views.sthos, name='sthos'),
    path('sthoscheck', views.sthoscheck, name='sthoscheck'),
    path('staffpermiss', views.staffpermiss, name='staffpermiss'),
    path('permission/<Pid>', views.permission, name='permission'),
    path('canpermission/<Pid>', views.canpermission, name='canpermission'),
    path('addtime', views.addtime, name='addtime'),
    path('staffmoniter', views.staffmoniter, name='staffmoniter'),
    path('editperson', views.editperson, name='editperson'),
    path('editpersonan', views.editpersonan, name='editpersonan'),
    path('staffinfo', views.staffinfo, name='staffinfo'),
    path('staffcheck', views.staffcheck, name='staffcheck'),
    path('editstaff', views.editstaff, name='editstaff'),
    path('gettimestart', views.gettimestart, name='gettimestart'),
    path('doctor', views.doctor, name='doctor'),
    path('staffshow', views.staffshow, name='staffshow'),
    path('doctorshow', views.doctorshow, name='doctorshow'),
    path('deletetimehos', views.deletetimehos, name='deletetimehos'),
    path('bookingv2ck', views.bookingv2ck, name='bookingv2ck'),
    path('bookingv2ck2', views.bookingv2ck2, name='bookingv2ck2'),
    path('managecount', views.managecount, name='managecount'),
    path('addcount', views.addcount, name='addcount'),
    path('testcalendar', views.testcalendar, name='testcalendar'),
    path('doctorcheck', views.doctorcheck, name='doctorcheck'),
    path('testsubmit', views.testsubmit, name='testsubmit'),
    path('getdatevalue', views.getdatevalue, name='getdatevalue'),
    path('testses', views.testses, name='testses'),
    path('resetcount', views.resetcount, name='resetcount'),
    path('aaadadad', views.select, name='select'),
    path('aaaa', views.checkad, name='checkad'),
    path('getdatebooking', views.getdatebooking, name='getdatebooking'),
    path('filterbooking', views.filterbooking, name='filterbooking'),
    path('calendar', views.calendar, name='calendar'),
    path('bookingevent', views.bookingevent, name='bookingevent'),
    path('bookingeventan', views.bookingeventan, name='bookingeventan'),
    path('bookingeventan2', views.bookingeventan2, name='bookingeventan2'),
    path('filterstaffmoniter', views.filterstaffmoniter, name='filterstaffmoniter'),
    path('verifybooking', views.verifybooking, name='verifybooking'),
    path('verifydontbooking', views.verifydontbooking, name='verifydontbooking'),
    path('stmcheck', views.stmcheck, name='stmcheck'),
    path('vtfbooking', views.vtfbooking, name='vtfbooking'),
    path('vtfbooking2', views.vtfbooking2, name='vtfbooking2'),
    path('callqueue', views.callqueue, name='callqueue'),
    path('callqueueck', views.callqueueck, name='callqueueck'),
    path('filtercallqueue', views.filtercallqueue, name='filtercallqueue'),
    path('callqueueup', views.callqueueup, name='callqueueup'),
    path('callqueuemail', views.callqueuemail, name='callqueuemail'),
    path('callqueuemail2/<bkid>', views.callqueuemail2, name='callqueuemail2'),
    path('reed', views.reed, name='reed'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('indexan', views.indexan, name='indexan'),
    path('infoan', views.infoan, name='infoan'),
    path('historyan', views.historyan, name='historyan'),
    path('hnan', views.hnan, name='hnan'),
    path('bkan', views.bkan, name='bkan'),
    path('scbkan', views.scbkan, name='scbkan'),
    path('addhnan', views.addhnan, name='addhnan'),
    path('settinghns', views.settinghns, name='settinghns'),
    path('fiterbookan', views.fiterbookan, name='fiterbookan'),
    path('filtermodal', views.filtermodal, name='filtermodal'),
    path('getdatedb', views.getdatedb, name='getdatedb'),
    path('hnud', views.hnud, name='hnud'),
    path('filterdashboard', views.filterdashboard, name='filterdashboard'),
    path('checkqueue', views.checkqueue, name='checkqueue'),
    path('settingHNweb/<Hnid>', views.settingHNweb, name='settingHNweb'),
    path('settinghnx/<Hnid>', views.settinghnx, name='settinghnx'),
    path('checkad2', views.checkad2, name='checkad2'),
    path('settingHNwebx/<Hnid>', views.settingHNwebx, name='settingHNwebx'),
    path('bookingevent2/<re_dep>/<re_sta>/<re_hos>', views.getdatebooking2, name='bookingevent2'),
    path('callqueue2', views.callqueue2, name='callqueue2'),
    path('historybooks', views.historybooks, name='historybooks'),
    path('sentmailnoti', views.sentmailnoti, name='sentmailnoti'),
    path('sentmailverti', views.sentmailverti, name='sentmailverti'),
    path('testline', views.testline, name='testline'),
    path('infouser', views.infouser, name='infouser'),
    path('tagdpm', views.tagdpm, name='tagdpm'),
    path('addtags', views.addtags, name='addtags'),
    path('edittags', views.edittags, name='edittags'),
    path('deletetags', views.deletetags, name='deletetags'),
    path('showtags', views.showtags, name='showtags'),
    path('tagssearch', views.tagssearch, name='tagssearch'),
    path('replazex', views.replazex, name='replazex'),
    path('replazecount', views.replazecount, name='replazecount'),
    path('calendarridirec', views.calendarridirec, name='calendarridirec'),
]