# Generated by Django 3.1.7 on 2021-03-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoQs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HNpid', models.CharField(max_length=30)),
                ('HNhid', models.IntegerField(max_length=30)),
                ('HN', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('HNpid', 'HNhid')},
            },
        ),
    ]
